name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t inbaanbu1998/git_action_project_2 .
      - name: Publish image to docker hub
        run: docker push inbaanbu1998/git_action_project_2:latest
  deploy:
    needs: build
    runs-on: ["aws-ec2"]
    steps:
      - name: Install Docker on the runner
        run: |
          sudo yum install -y docker
          sudo service docker start
          sudo systemctl enable docker
      - name: Pull Image from Docker Hub
        run: docker pull inbaanbu1998/git_action_project_2:latest
      - name: Stop and Remove old container (if exists)
        run: docker stop git_action_project_2-container || true && docker rm git_action_project_2-container || true
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name git_action_project_2-container inbaanbu1998/git_action_project_2:latest
